
# API Login credentials
consumer_key:
consumer_secret:
access_token:
access_secret:

# Save location, file name and extension for collected data
save_dir:
save_extension: ".zip"

# How often this config will be reloaded by the listener (minutes)
config_reload_interval: 15

# Additionally store tweets in MongoDB
use_mongo: False

# For every tweet with mentions, look up each mention's full user data
full_user_mentions: True

# When performing user lookups, cache the user and don't check again for this
# interval (minutes)
user_lookup_interval: 15
